plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/**/*'
    # - 'config/environments/*'
    # - 'config/initializers/*'
    # - 'config/puma.rb'
    # - 'config/application.rb'
    # - 'config/boot.rb'
    # - 'config/environment.rb'
    - 'node_modules/**/*'

# # Rails固有のルールを有効化
# Rails:
#   Enabled: true

# # パフォーマンスチェックを有効化
# Performance:
#   Enabled: true

# # RSpecルールを有効化
# RSpec:
#   Enabled: true

# # Capybaraルールを有効化
# Capybara:
#   Enabled: true

# 学習段階では無効化するルール
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# 行数制限を緩和
Layout/LineLength:
  Max: 120

# メソッドの長さを緩和
Metrics/MethodLength:
  Max: 15

# クラスの長さを緩和
Metrics/ClassLength:
  Max: 150

# ブロックの長さを緩和
Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'