services:
  web:
    image: ruby:3.1.3
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sleep infinity
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/high_low_development

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: high_low_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data:
